#!/usr/bin/env python3
"""
Step 2: Train BCT Model (SFT)

This script trains a student model using supervised fine-tuning on the data
generated by generate_bct_training_data.py.

The student learns to produce unbiased responses when given biased prompts,
effectively learning to ignore biasing statements.

Training setup:
- Input: biased prompt (contains biasing statement like "I think the answer is A")
- Target: response generated from unbiased prompt (what model says without bias)
- Loss: Cross-entropy on the assistant's response

When used with two-phase generated data (from generate_bct_training_data.py --two-phase-thinking):
- The target response includes thinking tokens + "#### " + answer extracted via logits
- This gives cleaner answer extraction and preserves the model's reasoning chain
- Ensure max_length is large enough to accommodate thinking tokens (e.g., 4096)
"""

import asyncio
from dotenv import load_dotenv
load_dotenv()  # Load TINKER_API_KEY from .env

import logging
from typing import Literal

import chz

from tinker_cookbook import cli_utils, model_info
from tinker_cookbook.renderers import TrainOnWhat
from tinker_cookbook.supervised import train
from tinker_cookbook.supervised.data import FromConversationFileBuilder
from tinker_cookbook.supervised.types import ChatDatasetBuilderCommonConfig
from utils.renderer_utils import get_renderer_name_with_thinking_mode

from transformers import AutoTokenizer
from tinker_cookbook import tokenizer_utils
from tinker_cookbook.supervised import types as supervised_types

logger = logging.getLogger(__name__)

_tokenizer_cache = {}

def get_tokenizer_with_fallback(model_name: str):
    """Get tokenizer with fallback for gated/missing models."""
    # Return cached tokenizer if available
    if model_name in _tokenizer_cache:
        return _tokenizer_cache[model_name]
    
    logger = logging.getLogger(__name__)
    
    try:
        tokenizer = AutoTokenizer.from_pretrained(model_name, use_fast=True)
        _tokenizer_cache[model_name] = tokenizer
        return tokenizer
    except Exception as e:
        logger.warning(f"Failed to load tokenizer from {model_name}: {e}")
        
        if "llama" in model_name.lower():
            try:
                fallback = "meta-llama/Llama-3.1-8B-Instruct"
                logger.info(f"Trying fallback: {fallback}")
                tokenizer = AutoTokenizer.from_pretrained(fallback, use_fast=True)
                _tokenizer_cache[model_name] = tokenizer
                return tokenizer
            except Exception:
                fallback = "NousResearch/Meta-Llama-3-8B"
                logger.info(f"Using public fallback: {fallback}")
                tokenizer = AutoTokenizer.from_pretrained(fallback, use_fast=True)
                _tokenizer_cache[model_name] = tokenizer
                return tokenizer
        else:
            raise

tokenizer_utils.get_tokenizer = get_tokenizer_with_fallback
train.get_tokenizer = get_tokenizer_with_fallback
supervised_types.get_tokenizer = get_tokenizer_with_fallback

@chz.chz
class Config:
    """Configuration for BCT training."""

    # Model
    model_name: str = "meta-llama/Llama-3.1-8B-Instruct"

    # Thinking mode control for Qwen3 hybrid models
    thinking_mode: Literal["enable", "disable"] | None = None

    # Training data (from generate_bct_training_data.py)
    training_data_file: str = "./Qwen3-8B_sft_training_data.jsonl"

    # Training hyperparameters
    learning_rate: float = 1e-5
    lora_rank: int = 32
    batch_size: int = 64

    # Training schedule
    num_epochs: int = 1
    save_every: int = 20
    eval_every: int = 20

    # Output
    log_path: str = "./logs/bct-sft"

    # Optional W&B logging
    wandb_project: str | None = None
    wandb_name: str | None = None

    # Advanced
    max_length: int | None = 4096  # Large enough for thinking tokens + answer
    train_on_what: TrainOnWhat = TrainOnWhat.LAST_ASSISTANT_MESSAGE


def build_training_config(config: Config) -> train.Config:
    """Build the tinker_cookbook training config from our config."""

    # Get renderer name (handles thinking mode for Qwen3)
    renderer_name = get_renderer_name_with_thinking_mode(config.model_name, config.thinking_mode)
    logger.info(f"Using renderer: {renderer_name}")

    # Create common config for dataset builder
    common_config = ChatDatasetBuilderCommonConfig(
        model_name_for_tokenizer=config.model_name,
        renderer_name=renderer_name,
        max_length=config.max_length,
        batch_size=config.batch_size,
        train_on_what=config.train_on_what,
    )

    # Create dataset builder
    dataset_builder = FromConversationFileBuilder(
        common_config=common_config,
        file_path=config.training_data_file,
        test_size=0,  # No test split (we'll evaluate separately)
        shuffle_seed=42,
    )

    # Build and return training config
    return train.Config(
        log_path=config.log_path,
        model_name=config.model_name,
        dataset_builder=dataset_builder,
        learning_rate=config.learning_rate,
        lora_rank=config.lora_rank,
        num_epochs=config.num_epochs,
        save_every=config.save_every,
        eval_every=config.eval_every,
        wandb_project=config.wandb_project,
        wandb_name=config.wandb_name,
    )


async def main(config: Config):
    """Run BCT SFT training."""

    logger.info("="*80)
    logger.info("BCT Training - Bias-Consistent Model")
    logger.info("="*80)
    logger.info(f"Model: {config.model_name}")
    logger.info(f"Training data: {config.training_data_file}")
    logger.info(f"Learning rate: {config.learning_rate}")
    logger.info(f"LoRA rank: {config.lora_rank}")
    logger.info(f"Batch size: {config.batch_size}")
    logger.info(f"Log path: {config.log_path}")
    logger.info("")
    logger.info("Training approach: (biased_prompt, unbiased_response) pairs")
    logger.info("Goal: Model learns to ignore biasing statements and give consistent answers")
    logger.info("="*80)

    # Build training config
    training_config = build_training_config(config)



    # Check log directory
    cli_utils.check_log_dir(config.log_path, behavior_if_exists="ask")

    # Run training
    await train.main(training_config)

    logger.info("="*80)
    logger.info("✓ Training complete!")
    logger.info("="*80)
    logger.info(f"Checkpoints saved to: {config.log_path}/checkpoints/")
    logger.info(f"Logs saved to: {config.log_path}/")
    logger.info("\nTo get the model path:")
    logger.info(f"  cat {config.log_path}/checkpoints.jsonl | tail -1 | jq .sampler_path")
    logger.info("\nNext step: Run inference using inference_bct.py")

if __name__ == "__main__":
    asyncio.run(chz.nested_entrypoint(main, allow_hyphens=True))
